### PR TITLE
syncoid: Sort snapshots by `createtxg` if possible (fallback to `creation`) (redux of #818)

### LINKED ISSUE #815: Syncoid: Data loss because `getoldestsnapshot()` might not choose the first snapshot
## Bug Description
Due to an incorrect clock at the time, I have some snapshots where the `creation` property is in the past compared to earlier snapshots.

When `syncoid` performs an initial full transfer of a dataset, it could select a snapshot that isn't the first snapshot of the dataset because of [the usage of `getoldestsnapshot()`](https://github.com/jimsalterjrs/sanoid/blob/86fffca306ecd0e5bdb7eb413f4970024f96b53f/syncoid#L425).  This leads to data loss, as some snapshots may be left behind.

## How to Reproduce

See the bold parts of the output below:

<pre><code>root@box52:&#x7E;# truncate -s64M /tmp/jimsalterjrs_sanoid_815.img
root@box52:&#x7E;# zpool create jimsalterjrs_sanoid_815 /tmp/jimsalterjrs_sanoid_815.img
root@box52:&#x7E;# zfs create jimsalterjrs_sanoid_815/before
root@box52:&#x7E;# zfs snap jimsalterjrs_sanoid_815/before@this-snapshot-does-not-make-it-into-the-after-dataset
root@box52:&#x7E;# date --set="2006-08-14T02:34:56-06:00" ; zfs snap jimsalterjrs_sanoid_815/before@oldest-snapshot ; date
Mon Aug 14 03:34:56 AM CDT 2006
Mon Aug 14 03:34:56 AM CDT 2006
root@box52:&#x7E;# systemctl restart systemd-timedated.service
root@box52:&#x7E;# date
Thu Apr 13 11:38:36 AM CDT 2023
root@box52:&#x7E;# zfs snap jimsalterjrs_sanoid_815/before@another-snapshot-does-not-matter
root@box52:&#x7E;# syncoid --sendoptions="Lec" jimsalterjrs_sanoid_815/{before,after}
INFO: Sending oldest full snapshot jimsalterjrs_sanoid_815/before@oldest-snapshot (&#x7E; 12 KB) to new target filesystem:
42.8KiB 0:00:00 [6.57MiB/s] [=============================================================================================] 339%            
INFO: Updating new target filesystem with incremental jimsalterjrs_sanoid_815/before@oldest-snapshot ... syncoid_box52.deltik.net_2023-04-13:11:38:51-GMT-05:00 (&#x7E; 4 KB):
2.13KiB 0:00:00 [ 136KiB/s] [================================================>                                             ] 53%            
root@box52:&#x7E;# zfs list -rtall jimsalterjrs_sanoid_815
NAME                                                                                       USED  AVAIL     REFER  MOUNTPOINT
jimsalterjrs_sanoid_815                                                                    229K  23.8M       25K  /jimsalterjrs_sanoid_815
jimsalterjrs_sanoid_815/after                                                               24K  23.8M       24K  /jimsalterjrs_sanoid_815/after
jimsalterjrs_sanoid_815/after@oldest-snapshot                                                0B      -       24K  -
jimsalterjrs_sanoid_815/after@another-snapshot-does-not-matter                               0B      -       24K  -
jimsalterjrs_sanoid_815/after@syncoid_box52.deltik.net_2023-04-13:11:38:51-GMT-05:00         0B      -       24K  -
jimsalterjrs_sanoid_815/before                                                              24K  23.8M       24K  /jimsalterjrs_sanoid_815/before
<strong>jimsalterjrs_sanoid_815/before@this-snapshot-does-not-make-it-into-the-after-dataset</strong>         0B      -       24K  -
jimsalterjrs_sanoid_815/before@oldest-snapshot                                               0B      -       24K  -
jimsalterjrs_sanoid_815/before@another-snapshot-does-not-matter                              0B      -       24K  -
jimsalterjrs_sanoid_815/before@syncoid_box52.deltik.net_2023-04-13:11:38:51-GMT-05:00        0B      -       24K  -
root@box52:&#x7E;# zfs get -r creation jimsalterjrs_sanoid_815
NAME                                                                                      PROPERTY  VALUE                  SOURCE
jimsalterjrs_sanoid_815                                                                   creation  Thu Apr 13 11:37 2023  -
jimsalterjrs_sanoid_815/after                                                             creation  Thu Apr 13 11:38 2023  -
jimsalterjrs_sanoid_815/after@oldest-snapshot                                             creation  Mon Aug 14  3:34 2006  -
jimsalterjrs_sanoid_815/after@another-snapshot-does-not-matter                            creation  Thu Apr 13 11:38 2023  -
jimsalterjrs_sanoid_815/after@syncoid_box52.deltik.net_2023-04-13:11:38:51-GMT-05:00      creation  Thu Apr 13 11:38 2023  -
jimsalterjrs_sanoid_815/before                                                            creation  Thu Apr 13 11:37 2023  -
<strong>jimsalterjrs_sanoid_815/before@this-snapshot-does-not-make-it-into-the-after-dataset</strong>      creation  <strong>Thu Apr 13 11:38 2023</strong>  -
<strong>jimsalterjrs_sanoid_815/before@oldest-snapshot</strong>                                            creation  <strong>Mon Aug 14  3:34 2006</strong>  -
jimsalterjrs_sanoid_815/before@another-snapshot-does-not-matter                           creation  Thu Apr 13 11:38 2023  -
jimsalterjrs_sanoid_815/before@syncoid_box52.deltik.net_2023-04-13:11:38:51-GMT-05:00     creation  Thu Apr 13 11:38 2023  -
root@box52:&#x7E;# zpool export jimsalterjrs_sanoid_815
root@box52:&#x7E;# rm -fv /tmp/jimsalterjrs_sanoid_815.img
removed '/tmp/jimsalterjrs_sanoid_815.img'</code></pre>

## Expected Behavior
All snapshots are copied in the initial full sync, not just from the oldest-by-`creation` snapshot onwards.

### PR DESCRIPTION
**Pull request by Deltik**
## Motivation and Context

This pull request addresses the same underlying issue as the [reverted](https://github.com/jimsalterjrs/sanoid/commit/b794da6f145fdeb8ff1e48d267629cc51193470c) #818: #815 (_Syncoid: Data loss because getoldestsnapshot() might not choose the first snapshot_).  This remake incorporates the new approach from #931 to avoid the performance regressions and bugs that caused #818 to be reverted in b794da6f145fdeb8ff1e48d267629cc51193470c.

The original problem remains in [Syncoid v2.3.0](https://github.com/jimsalterjrs/sanoid/releases/tag/v2.3.0): When system clocks are adjusted (due to NTP sync, manual changes, etc.), ZFS snapshot `creation` timestamps can become non-monotonic.  This causes `syncoid`'s `getoldestsnapshot()` and `getnewestsnapshot()` functions to select incorrect snapshots, potentially leading to missing data during initial replication or when using `--no-sync-snap`.

## Description

This new implementation reworks the approach taken in #818, addressing both the original issue and the regressions that led to its revert:

### fix(syncoid): Rework snap/bookmark fetching with feature detection

The original snapshot fetching relied on a complex state-dependent
`getsnaps()` subroutine with a separate `getsnapsfallback()` for older
ZFS versions. The first refactor attempt in #818 simplified this but
introduced performance regressions by using `zfs get all`, which was
inefficient for large datasets.

This commit avoids that overhead by integrating proactive `zfs get`
feature detection through a new `check_zfs_get_features()` subroutine
that determines the command's capabilities by testing for `-t` (type
filter) support and the availability of the `createtxg` property.
Results are cached per host to avoid redundant checks.
`check_zfs_get_features()` came from the #931, which this change
supersedes.

The `getsnaps()` and `getbookmarks()` subroutines now use this
information to build optimized `zfs get` commands that query only
necessary properties. As before in #818, the parsing logic is refactored
to populate property hashes for each item, eliminating the old
multi-loop state-dependent approach and the need for mostly duplicated
fallback logic.

This resolves both the original complexity and the performance issues
from the first attempted fix. Now there is a foundation for fixing the
snapshot ordering bug reported in #815.

### feat(syncoid): Sort snapshots reliably using the `createtxg` property

System clock adjustments from manual changes or NTP synchronization can 
cause ZFS snapshot creation timestamps to be non-monotonic. This can 
cause `syncoid` to select the wrong "oldest" snapshot for initial 
replication or the wrong "newest" snapshot with `--no-sync-snap`, 
potentially losing data from the source to the target.

This change adds the `sortsnapshots()` helper that prefers to compare 
the `createtxg` (creation transaction group) property over the 
`creation` property when available. The `createtxg` property is 
guaranteed to be strictly sequential within a ZFS pool, unlike the 
`creation` property, which depends on the system clock's accuracy.

Unlike the first iteration of `sortsnapshots()` in #818, the subroutine 
takes a specific snapshot sub-hash ('source' or 'target') as input 
rather than both, ensuring createtxg comparisons occur within the same 
zpool context. The first iteration that took the entire snapshots hash 
had no mechanism to sort target snapshots, which could have caused 
issues in usages that expected target snapshots to be sorted.

Most snapshot sorting call sites now use the new `sortsnapshots()`
subroutine. Two more usages involving bookmarks are updated in a
different commit for independent testing of a bookmarks-related
refactoring.

Fixes: #815

### fix(syncoid): Harden bookmark replication against timestamp non-monotony

* Replaced direct sorting on the `creation` property with calls to the
  `sortsnapshots()` helper subroutine. As with other usages, this
  ensures that when `syncoid` searches for the next snapshot to
  replicate from a bookmark, it preferentially uses the monotonic
  `createtxg` for sorting.
* Refactored the variables holding bookmark details from separate
  scalars (`$bookmark`, `$bookmarkcreation`) into a single hash
  (`%bookmark`). This allows for cleaner handling of all
  relevant bookmark properties (`name`, `creation`, `createtxg`).
* Fixed a code comment that incorrectly described the snapshot search
  order. The search for a matching target snapshot now correctly states
  it proceeds from newest-to-oldest to find the most recent common
  ancestor.

### test(syncoid): Add test to verify out-of-order snapshot sync

This commit adds a regression test for the out-of-order snapshot
replication issue.

The new test case manipulates the system clock with `setdate` to create
snapshots with non-monotonic `creation` timestamps but a correct,
sequential `createtxg`. It then runs `syncoid` and verifies that all
snapshots were replicated, which is only possible if they are ordered
correctly by `createtxg`.

See #815 for the original test.

### fix(tests/common/lib.sh): Support set -e in test scripts

The `systemctl is-active virtualbox-guest-utils.service` command returns
a non-zero exit status when the service is inactive, causing early exit
in tests that use `set -e`.

This change suppresses that error with `|| true` to prevent test failure
when the service check returns non-zero.

Fixes this test:

```
root@demo:~/sanoid/tests/syncoid# cat /tmp/syncoid_test_run_011_sync_out-of-order_snapshots.log
+ set -e
+ . ../../common/lib.sh
+++ uname
++ unamestr=Linux
+ POOL_IMAGE=/tmp/jimsalterjrs_sanoid_815.img
+ POOL_SIZE=64M
+ POOL_NAME=jimsalterjrs_sanoid_815
+ truncate -s 64M /tmp/jimsalterjrs_sanoid_815.img
+ zpool create -m none -f jimsalterjrs_sanoid_815 /tmp/jimsalterjrs_sanoid_815.img
+ trap cleanUp EXIT
+ zfs create jimsalterjrs_sanoid_815/before
+ zfs snapshot jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset
+ disableTimeSync
+ which timedatectl
+ '[' 0 -eq 0 ']'
+ timedatectl set-ntp 0
+ which systemctl
+ '[' 0 -eq 0 ']'
+ systemctl is-active virtualbox-guest-utils.service
inactive
+ cleanUp
+ zpool export jimsalterjrs_sanoid_815
+ rm -f /tmp/jimsalterjrs_sanoid_815.img
```

## Related Issues

This pull request redoes #818 to fix #815 by integrating #931 and fixing one additional issue that went unnoticed in those previous pull requests:

1. `sortsnapshots()` was not able to sort target snapshots but can now do so.

## How Has This Been Tested?

All existing `syncoid` tests pass, plus the new regression test for out-of-order snapshots:

Before:

```shell
root@demo:~/sanoid/tests/syncoid# git checkout origin/fix/815 /root/sanoid/tests/common/lib.sh
Updated 1 path from 021cbc7
root@demo:~/sanoid/tests/syncoid# ./run-tests.sh
Running test 001_bookmark_replication_intermediate ... [PASS]
Running test 002_bookmark_replication_no_intermediate ... [PASS]
Running test 003_force_delete ... [PASS]
Running test 004_bookmark_replication_edge_case ... [PASS]
Running test 005_reset_resume_state ... mbuffer: error: outputThread: error writing to <stdout> at offset 0x40000: Broken pipe
mbuffer: warning: error during output to <stdout>: Broken pipe
[PASS]
Running test 006_reset_resume_state2 ... [PASS]
Running test 007_preserve_recordsize ... [PASS]
Running test 008_force_delete_snapshot ... [PASS]
Running test 009_preserve_properties ... [PASS]
Running test 010_filter_snaps ... [PASS]
Running test 011_sync_out-of-order_snapshots ... [FAILED] (see /tmp/syncoid_test_run_011_sync_out-of-order_snapshots.log)
Running test 012_receive_resume_token ... [PASS]
root@demo:~/sanoid/tests/syncoid# cat /tmp/syncoid_test_run_011_sync_out-of-order_snapshots.log
+ set -e
+ . ../../common/lib.sh
+++ uname
++ unamestr=Linux
+ POOL_IMAGE=/tmp/jimsalterjrs_sanoid_815.img
+ POOL_SIZE=64M
+ POOL_NAME=jimsalterjrs_sanoid_815
+ truncate -s 64M /tmp/jimsalterjrs_sanoid_815.img
+ zpool create -m none -f jimsalterjrs_sanoid_815 /tmp/jimsalterjrs_sanoid_815.img
+ trap cleanUp EXIT
+ zfs create jimsalterjrs_sanoid_815/before
+ zfs snapshot jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset
+ disableTimeSync
+ which timedatectl
+ '[' 0 -eq 0 ']'
+ timedatectl set-ntp 0
+ which systemctl
+ '[' 0 -eq 0 ']'
+ systemctl is-active virtualbox-guest-utils.service
inactive
+ true
+ setdate 1155533696
+ TIMESTAMP=1155533696
+ '[' Linux == FreeBSD ']'
+ date --utc --set @1155533696
Mon Aug 14 05:34:56 UTC 2006
+ zfs snapshot jimsalterjrs_sanoid_815/before@oldest-snapshot
+ zfs snapshot jimsalterjrs_sanoid_815/before@another-snapshot-does-not-matter
+ ../../../syncoid --sendoptions=Lec jimsalterjrs_sanoid_815/before jimsalterjrs_sanoid_815/after
INFO: Sending oldest full snapshot jimsalterjrs_sanoid_815/before@oldest-snapshot to new target filesystem jimsalterjrs_sanoid_815/after (~ 12 KB):
INFO: Sending incremental jimsalterjrs_sanoid_815/before@oldest-snapshot ... syncoid_demo_2006-08-14:05:34:56-GMT00:00 to jimsalterjrs_sanoid_815/after (~ 4 KB):
+ saveSnapshotList jimsalterjrs_sanoid_815 snapshot-list.txt
+ POOL_NAME=jimsalterjrs_sanoid_815
+ RESULT=snapshot-list.txt
+ zfs list -t snapshot -o name -Hr jimsalterjrs_sanoid_815
+ sort
+ '[' Linux == FreeBSD ']'
+ sed -i 's/\(autosnap_[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9]:[0-9][0-9]:\)[0-9][0-9]/\100/g' snapshot-list.txt
+ grep jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset snapshot-list.txt
jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset
+ grep jimsalterjrs_sanoid_815/after@this-snapshot-should-make-it-into-the-after-dataset snapshot-list.txt
+ exit 1
+ cleanUp
+ zpool export jimsalterjrs_sanoid_815
+ rm -f /tmp/jimsalterjrs_sanoid_815.img
```

After:

```shell
root@demo:~/sanoid/tests/syncoid# ./run-tests.sh
Running test 001_bookmark_replication_intermediate ... [PASS]
Running test 002_bookmark_replication_no_intermediate ... [PASS]
Running test 003_force_delete ... [PASS]
Running test 004_bookmark_replication_edge_case ... [PASS]
Running test 005_reset_resume_state ... mbuffer: error: outputThread: error writing to <stdout> at offset 0x20000: Broken pipe
mbuffer: warning: error during output to <stdout>: Broken pipe
[PASS]
Running test 006_reset_resume_state2 ... [PASS]
Running test 007_preserve_recordsize ... [PASS]
Running test 008_force_delete_snapshot ... [PASS]
Running test 009_preserve_properties ... [PASS]
Running test 010_filter_snaps ... [PASS]
Running test 011_sync_out-of-order_snapshots ... [PASS]
Running test 012_receive_resume_token ... [PASS]
root@demo:~/sanoid/tests/syncoid# cat /tmp/syncoid_test_run_011_sync_out-of-order_snapshots.log
+ set -e
+ . ../../common/lib.sh
+++ uname
++ unamestr=Linux
+ POOL_IMAGE=/tmp/jimsalterjrs_sanoid_815.img
+ POOL_SIZE=64M
+ POOL_NAME=jimsalterjrs_sanoid_815
+ truncate -s 64M /tmp/jimsalterjrs_sanoid_815.img
+ zpool create -m none -f jimsalterjrs_sanoid_815 /tmp/jimsalterjrs_sanoid_815.img
+ trap cleanUp EXIT
+ zfs create jimsalterjrs_sanoid_815/before
+ zfs snapshot jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset
+ disableTimeSync
+ which timedatectl
+ '[' 0 -eq 0 ']'
+ timedatectl set-ntp 0
+ which systemctl
+ '[' 0 -eq 0 ']'
+ systemctl is-active virtualbox-guest-utils.service
inactive
+ true
+ setdate 1155533696
+ TIMESTAMP=1155533696
+ '[' Linux == FreeBSD ']'
+ date --utc --set @1155533696
Mon Aug 14 05:34:56 UTC 2006
+ zfs snapshot jimsalterjrs_sanoid_815/before@oldest-snapshot
+ zfs snapshot jimsalterjrs_sanoid_815/before@another-snapshot-does-not-matter
+ ../../../syncoid --sendoptions=Lec jimsalterjrs_sanoid_815/before jimsalterjrs_sanoid_815/after
INFO: Sending oldest full snapshot jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset to new target filesystem jimsalterjrs_sanoid_815/after (~ 12 KB):
INFO: Sending incremental jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset ... syncoid_demo_2006-08-14:05:34:56-GMT00:00 to jimsalterjrs_sanoid_815/after (~ 4 KB):
+ saveSnapshotList jimsalterjrs_sanoid_815 snapshot-list.txt
+ POOL_NAME=jimsalterjrs_sanoid_815
+ RESULT=snapshot-list.txt
+ zfs list -t snapshot -o name -Hr jimsalterjrs_sanoid_815
+ sort
+ '[' Linux == FreeBSD ']'
+ sed -i 's/\(autosnap_[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9]:[0-9][0-9]:\)[0-9][0-9]/\100/g' snapshot-list.txt
+ grep jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset snapshot-list.txt
jimsalterjrs_sanoid_815/before@this-snapshot-should-make-it-into-the-after-dataset
+ grep jimsalterjrs_sanoid_815/after@this-snapshot-should-make-it-into-the-after-dataset snapshot-list.txt
jimsalterjrs_sanoid_815/after@this-snapshot-should-make-it-into-the-after-dataset
+ grep jimsalterjrs_sanoid_815/before@oldest-snapshot snapshot-list.txt
jimsalterjrs_sanoid_815/before@oldest-snapshot
+ grep jimsalterjrs_sanoid_815/after@oldest-snapshot snapshot-list.txt
jimsalterjrs_sanoid_815/after@oldest-snapshot
+ grep jimsalterjrs_sanoid_815/before@another-snapshot-does-not-matter snapshot-list.txt
jimsalterjrs_sanoid_815/before@another-snapshot-does-not-matter
+ grep jimsalterjrs_sanoid_815/after@another-snapshot-does-not-matter snapshot-list.txt
jimsalterjrs_sanoid_815/after@another-snapshot-does-not-matter
+ exit 0
+ cleanUp
+ zpool export jimsalterjrs_sanoid_815
+ rm -f /tmp/jimsalterjrs_sanoid_815.img
```

I manually tested the [`zfs get`](https://openzfs.github.io/openzfs-docs/man/master/8/zfs-get.8.html) feature detection feature on an old ZFS pool version 28 / ZFS file system version 5 setup in FreeBSD 8.3:

```
[root@FREEBSD ~/sanoid]# sysctl vfs.zfs.version
vfs.zfs.version.zpl: 5
vfs.zfs.version.spa: 28
vfs.zfs.version.acl: 1
```

On this FreeBSD 8.3 machine, I created some dummy snapshots:

```
[root@FREEBSD ~/sanoid]# zfs list -rtall
NAME                                                               USED  AVAIL  REFER  MOUNTPOINT
rpool                                                              224M   760M    32K  /rpool
rpool/before                                                       224M   760M  32.1M  /rpool/before
rpool/before@this-snapshot-should-make-it-into-the-after-dataset   128M      -   128M  -
rpool/before@a-snapshot                                           64.1M      -  64.1M  -
rpool/before@another-snapshot                                         0      -  32.1M  -
```

And `syncoid` was able to transfer them out:

```
root@workstation [~]# ./syncoid --debug root@192.168.122.70:rpool/before syncoid-test-11/after
DEBUG: SSHCMD: ssh     
Warning: Permanently added '192.168.122.70' (RSA) to the list of known hosts.
(root@192.168.122.70) Password:
DEBUG: checking availability of lzop on source...
DEBUG: checking availability of lzop on target...
DEBUG: checking availability of lzop on local machine...
WARNING: lzop not available on source ssh:-S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70- sync will continue without compression.
DEBUG: checking availability of mbuffer on source...
WARNING: mbuffer not available on source ssh:-S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70 - sync will continue without source buffering.
DEBUG: checking availability of mbuffer on target...
DEBUG: checking availability of pv on local machine...
DEBUG: checking availability of zfs resume feature on source...
DEBUG: checking availability of zfs resume feature on target...
WARNING: ZFS resume feature not available on source machine - sync will continue without resume support.
DEBUG: syncing source rpool/before to target syncoid-test-11/after.
DEBUG: getting current value of syncoid:sync on rpool/before...
DEBUG: ssh      -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70  zfs get -H syncoid:sync ''"'"'rpool/before'"'"''
DEBUG: checking to see if syncoid-test-11/after on  is already in zfs receive using  ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using "  zfs get -H name 'syncoid-test-11/after' 2>&1 |"...
DEBUG: Checking `zfs get` features on host "root@192.168.122.70"...
DEBUG: Host "root@192.168.122.70" has `zfs get -t`?: 0
DEBUG: Host "root@192.168.122.70" ZFS properties: guid creation createtxg
DEBUG: getting list of snapshots on rpool/before using ssh      -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70  zfs get -Hpd 1  guid,creation,createtxg,type ''"'"'rpool/before'"'"'' |...
DEBUG: creating sync snapshot using "ssh      -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70  zfs snapshot ''"'"'rpool/before'"'"''@syncoid_workstation.wizard2.net_2025-06-11:23:49:29-GMT-05:00
"...
DEBUG: target syncoid-test-11/after does not exist.  Finding oldest available snapshot on source rpool/before ...
DEBUG: getting estimated transfer size from source -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70 using "ssh      -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70  zfs send  -nvP ''"'"'rpool/before@this-snapshot-should-make-it-into-the-after-dataset'"'"'' 2>&1 |"...
DEBUG: sendsize = 134470344
INFO: Sending oldest full snapshot root@192.168.122.70:rpool/before@this-snapshot-should-make-it-into-the-after-dataset to new target filesystem syncoid-test-11/after (~ 128.2 MB):
DEBUG: sync size: ~128.2 MB
DEBUG: ssh      -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70 ' zfs send  '"'"'rpool/before'"'"'@'"'"'this-snapshot-should-make-it-into-the-after-dataset'"'"'' | mbuffer  -q -s 128k -m 16M | pv -p -t -e -r -b -s 134470344 |  zfs receive  -F 'syncoid-test-11/after' 2>&1
DEBUG: checking to see if syncoid-test-11/after on  is already in zfs receive using  ps -Ao args= ...
 128MiB 0:00:02 [44.0MiB/s] [============================================================================================================================================================================================================================================>] 100%            
DEBUG: getting estimated transfer size from source -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70 using "ssh      -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70  zfs send  -nvP -I ''"'"'rpool/before@this-snapshot-should-make-it-into-the-after-dataset'"'"'' ''"'"'rpool/before@syncoid_workstation.wizard2.net_2025-06-11:23:49:29-GMT-05:00'"'"'' 2>&1 |"...
DEBUG: sendsize = 100858256
INFO: Sending incremental root@192.168.122.70:rpool/before@this-snapshot-should-make-it-into-the-after-dataset ... syncoid_workstation.wizard2.net_2025-06-11:23:49:29-GMT-05:00 to syncoid-test-11/after (~ 96.2 MB):
DEBUG: sync size: ~96.2 MB
DEBUG: ssh      -S /tmp/syncoid-root19216812270-1749703767-3334611-8120 root@192.168.122.70 ' zfs send  -I '"'"'rpool/before'"'"'@'"'"'this-snapshot-should-make-it-into-the-after-dataset'"'"' '"'"'rpool/before'"'"'@'"'"'syncoid_workstation.wizard2.net_2025-06-11:23:49:29-GMT-05:00'"'"'' | mbuffer  -q -s 128k -m 16M | pv -p -t -e -r -b -s 100858256 |  zfs receive  -F 'syncoid-test-11/after' 2>&1
DEBUG: checking to see if syncoid-test-11/after on  is already in zfs receive using  ps -Ao args= ...
96.2MiB 0:00:02 [40.7MiB/s] [============================================================================================================================================================================================================================================>] 100%            
root@workstation [~]# zfs list -rtall syncoid-test-11
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
syncoid-test-11                                                                       224M   608M    25K  /syncoid-test-11
syncoid-test-11/after                                                                 224M   608M  32.0M  /syncoid-test-11/after
syncoid-test-11/after@this-snapshot-should-make-it-into-the-after-dataset             128M      -   128M  -
syncoid-test-11/after@a-snapshot                                                     64.1M      -  64.1M  -
syncoid-test-11/after@another-snapshot                                                  0B      -  32.0M  -
syncoid-test-11/after@syncoid_workstation.wizard2.net_2025-06-11:23:49:29-GMT-05:00     0B      -  32.0M  -
```

## Types of Changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)  
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
@phreaker0 this looks good to me. Haven't had a chance to test the code directly yet, though.

File: syncoid [hunk 1]
```diff
@@ -1392,6 +1396,47 @@ sub checkcommands {
...
+	my $output_t = <$fh_t>;
+	close $fh_t;
+
+	if ($output_t !~ /^\Qinvalid option\E/) {
+		$host_zfs_get_features{$host}->{supports_type_filter} = 1;
+	}
+
+	writelog('DEBUG', "Host \"$host\" has `zfs get -t`?: $host_zfs_get_features{$host}->{supports_type_filter}");
+
+	my @properties_to_check = ('guid', 'creation', 'createtxg');
```
Comment (phreaker0) [inline syncoid:1423]: only check for createtxg. guid and creation needs to be there (was required before). Saves zfs execution calls.

File: syncoid [hunk 2]
```diff
@@ -1530,9 +1575,17 @@ sub readablebytes {
 	return $disp;
 }
 
+sub sortsnapshots {
+	my ($snapdata, $left, $right) = @_;
+	if (defined $snapdata->{$left}{'createtxg'} && defined $snapdata->{$right}{'createtxg'}) {
+		return $snapdata->{$left}{'createtxg'} <=> $snapdata->{$right}{'createtxg'};
+	}
+	return $snapdata->{$left}{'creation'} <=> $snapdata->{$right}{'creation'};
```
Comment (phreaker0) [inline syncoid:1583]: this reintroduces a regression (#962) which was addressed in #966

File: syncoid [hunk 3]
```diff
@@ -1883,142 +1945,48 @@ sub getsnaps() {
...
-			$state = -1;
+			$snap_data{$snap}{'creation'} = $creationsuffix;
 		}
+	}
 
-		$state++;
+	for my $snap (keys %snap_data) {
+		if (length $type_filter || $snap_data{$snap}{'type'} eq 'snapshot') {
+			$snaps{$type}{$snap}{'guid'} = $snap_data{$snap}{'guid'};
+			$snaps{$type}{$snap}{'createtxg'} = $snap_data{$snap}{'createtxg'};
```
Comment (phreaker0) [inline syncoid:1987]: wouldn't this throw a warning on systems which don't have the 'createtxg' property?

File: tests/run-tests.sh [hunk 4]
```diff
@@ -2,7 +2,7 @@
 
 # run's all the available tests
 
-for test in */; do
+for test in $(find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort -g); do
```
Comment (phreaker0) [inline tests/run-tests.sh:5]: not needed with the numbering scheme

File: tests/syncoid/815_sync_out-of-order_snapshots/run.sh
Comment (phreaker0) [inline tests/syncoid/815_sync_out-of-order_snapshots/run.sh:1]: please replace '815' to '011' so it's in line with the other tests.

File: tests/syncoid/run-tests.sh [hunk 5]
```diff
@@ -2,7 +2,7 @@
 
 # run's all the available tests
 
-for test in */; do
+for test in $(find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort -g); do
```
Comment (phreaker0) [inline tests/syncoid/run-tests.sh:5]: not needed with the numbering scheme

**Review by phreaker0 — CHANGES_REQUESTED** [review]
please address the comments and I will test the PR afterwards, thx

File: syncoid (hunk 3 above)
Comment (Deltik) [reply syncoid]: Fixed in [fixup](https://github.com/jimsalterjrs/sanoid/compare/eea2294e78872ea2932a01045196a5cdb85b736c..3443717b3b95f4cee62880b44b39ac067989c755#diff-683edffb56691d255a7fa767bfdfa90d294397460f39deddda506931afd5eaf5L1986-R1995)

File: tests/run-tests.sh (hunk 4 above)
Comment (Deltik) [reply tests/run-tests.sh]: [Commit dropped](https://github.com/jimsalterjrs/sanoid/compare/3443717b3b95f4cee62880b44b39ac067989c755..3d0571fe02204bffd9d9d41d05d31fcb71f1ec75)

File: tests/syncoid/run-tests.sh (hunk 5 above)
Comment (Deltik) [reply tests/syncoid/run-tests.sh]: [Commit dropped](https://github.com/jimsalterjrs/sanoid/compare/3443717b3b95f4cee62880b44b39ac067989c755..3d0571fe02204bffd9d9d41d05d31fcb71f1ec75)

**Comment by jimsalterjrs** [comment]
Hi @phreaker0 , are your concerns resolved?

**Comment by phreaker0** [comment]
@Deltik thx, i resolve the merge conflicts and adapted the test. I ran some test locally and it worked out so it can be merged for more testing.

**Comment by jimsalterjrs** [comment]
Merged. Let's try and get some more testing done on this in fairly short order; this is a fairly substantial change and I want to make sure we don't introduce gremlins in master--there are quite a few people running from master, because we generally keep master pretty stable. :)

**Comment by jimsalterjrs** [comment]
BTW @Deltik I appreciate the hustle. I know you worked on this for a long time and worked through a lot of requested changes, and I PARTICULARLY appreciate the way in the end you documented making sure we're still backwards compatible with v5000 pools and ZFS versions. <3

**Comment by phreaker0** [comment]
@Deltik i just found and issue. For ssh based replication the support check for the "createtxg" property will actually fetch all createtxg properties from all datasets/snapshots on the system.

**Comment by Deltik** [comment]
> @Deltik i just found and issue. For ssh based replication the support check for the "createtxg" property will actually fetch all createtxg properties from all datasets/snapshots on the system.

Thanks, @phreaker0.  I understand the cause clearly and have filed https://github.com/jimsalterjrs/sanoid/issues/1085 to track this new performance issue.
